server:
  port: 8002
spring:
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr:
  profiles:
    active: dev
aliyun:
  oss:
    file:
      endpoint:
      keyid:
      keysecret:
      bucketname: leaseplatform